# Config file for iProtector v4.0 by Kevin Andrews;
# Forked from the original LDX-MCPE/iProtector repository, now implementing new features
# and support for the PocketMine-MP API 3.0.0

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  DEFAULT:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false
